/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "background": "#faf8ff",
        "on-tertiary-fixed-variant": "#93000b",
        "secondary": "#4e5e82",
        "surface-variant": "#dae2fd",
        "on-primary-fixed-variant": "#394761",
        "tertiary-fixed": "#ffdad6",
        "surface-container-low": "#f2f3ff",
        "outline-variant": "#c5c6ce",
        "on-primary-container": "#7886a3",
        "on-tertiary": "#ffffff",
        "tertiary": "#140000",
        "secondary-fixed-dim": "#b6c6f0",
        "surface-dim": "#d2d9f4",
        "on-surface": "#131b2e",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "primary-fixed-dim": "#b8c7e6",
        "tertiary-fixed-dim": "#ffb4ab",
        "on-secondary-container": "#4b5b7f",
        "on-tertiary-container": "#f93d37",
        "surface-container": "#eaedff",
        "on-background": "#131b2e",
        "secondary-container": "#c4d4fe",
        "on-secondary-fixed-variant": "#364669",
        "inverse-surface": "#283044",
        "inverse-primary": "#b8c7e6",
        "primary-container": "#0f1e36",
        "surface-tint": "#515f7a",
        "on-tertiary-fixed": "#410002",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-bright": "#faf8ff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "primary": "#000412",
        "on-primary-fixed": "#0c1b33",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#071b3b",
        "secondary-fixed": "#d8e2ff",
        "on-primary": "#ffffff",
        "primary-fixed": "#d7e3ff",
        "on-secondary": "#ffffff",
        "outline": "#75777e",
        "surface": "#faf8ff",
        "on-surface-variant": "#44474d",
        "tertiary-container": "#460002",
        "on-error-container": "#93000a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "spacing-sm": "0.75rem",
        "spacing-2xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "margin-desktop": "1.5rem",
        "spacing-md": "1rem",
        "spacing-2xl": "2rem",
        "margin-mobile": "1rem",
        "spacing-xl": "1.5rem",
        "spacing-xs": "0.5rem",
        "gutter-desktop": "1rem",
        "spacing-3xs": "0.125rem",
        "spacing-3xl": "3rem",
        "spacing-lg": "1.25rem"
      },
      "fontFamily": {
        "headline-xl": ["Public Sans", "sans-serif"],
        "headline-sm": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "headline-xl-mobile": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "code-md": ["Public Sans", "sans-serif"],
        "label-lg": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "body-sm": ["Public Sans", "sans-serif"]
      }
    }
  },
  plugins: [],
}
